jdbcSettings:
  url: "jdbc:mysql://mysql.cc.puv.fi:3306/e1800917_springboot"
  username: "e1800917"
  password: "QjSbdggENEbu"
  driverClassName: "com.mysql.jdbc.Driver"

packageName: "fi.vamk.e1800917.spring3"